version: '3'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite

  function:
    build: .
    links:
      - azurite
    environment:
      AzureWebJobsStorage: "UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite"